- hosts: localhost

  vars:
    ansible_user: "lucas"

  tasks:
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/miniconda.yml
