- hosts: localhost
  become: true

  vars:
    ansible_user: "lucas"

  tasks:
    - name: Update system
      apt:
        update_cache: yes
        upgrade: dist

    - import_tasks: tasks/core.yml
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/npm-packages.yml
    - import_tasks: tasks/miniconda.yml
