- name: Install fzf
  become: true
  apt:
    name: fzf
    state: present

- name: Install gcc
  become: true
  apt:
    name: gcc
    state: present

- name: Install make
  become: true
  apt:
    name: make
    state: present

- name: Install curl
  become: true
  apt:
    name: curl
    state: present
    
- name: Install unzip
  become: true
  apt:
    name: unzip
    state: present

- name: Install libs
  become: true
  apt:
    name: ["libssl-dev", "libffi-dev"]
    state: present
