- name: Install build-essential
  apt:
    name: build-essential
    state: present

- name: Install unzip
  apt:
    name: unzip
    state: present

- name: Install curl
  apt:
    name: curl
    state: present

- name: Install fzf
  shell: "git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install --all"
  args:
    executable: /bin/bash

- name: Install tmux
  apt:
    name: tmux
    state: present
