- name: Ensure necessary packages are installed
  become: true
  apt:
    name:
      - gcc
      - make
      - curl
      - unzip
      - fzf
    state: present
    update_cache: yes
  tags:
    - packages
