- name: Install stow
  become: true
  apt:
    name: stow
    state: present
    
- name: Create projects folder
  shell: mkdir -p /home/{{ ansible_user }}/projects

- name: Clone dotfiles repository
  git:
    repo: "git@github.com:lucaspellegrinelli/dotfiles.git"
    dest: "/home/{{ ansible_user }}/projects/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    key_file: "/home/{{ ansible_user }}/.ssh/id_rsa"
    version: main

- name: Clone bhub dotfiles repository
  git:
    repo: "git@github.com:lucaspellegrinelli/dotfiles-bhub.git"
    dest: "/home/{{ ansible_user }}/projects/dotfiles-bhub"
    recursive: yes
    update: yes
    accept_hostkey: yes
    key_file: "/home/{{ ansible_user }}/.ssh/id_rsa"
    version: main

- name: Stow dotfiles
  shell: "cd /home/{{ ansible_user }}/projects/dotfiles && stow */"
  args:
    executable: /bin/bash

- name: Stow bhub dotfiles
  shell: "cd /home/{{ ansible_user }}/projects/dotfiles-bhub && stow */"
  args:
    executable: /bin/bash
