- name: Install stow
  become: true
  apt:
    name: stow
    state: present

- name: Clone dotfiles repository
  git:
    repo: "git@github.com:lucaspellegrinelli/dotfiles.git"
    dest: "~/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    key_file: "~/.ssh/id_rsa"
    version: main

- name: Stow dotfiles
  shell: "cd ~/dotfiles && stow */"
  args:
    executable: /bin/bash
