- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:lucaspellegrinelli/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
