- name: Install git
  become: true
  apt:
    name: git
    update_cache: yes
    state: present
  tags:
    - git

- name: Set git username and email
  shell: |
    git config --global user.name "{{ git_username }}"
    git config --global user.email "{{ git_email }}"
  vars:
    git_username: "Lucas Pellegrinelli"
    git_email: "lucas.pellegrinelli@hotmail.com"
  tags:
    - git
