- name: Download Miniconda installer
  get_url:
    url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    dest: "/tmp/miniconda.sh"
    mode: '0755'

- name: Update miniconda directory owner
  become: true
  shell: "chown -R {{ ansible_user }}:{{ ansible_user }} /opt/"

- name: Install Miniconda
  shell: "/tmp/miniconda.sh -b -p /opt/miniconda"

- name: Remove Miniconda installer
  file:
    path: /tmp/miniconda.sh
    state: absent

- name: Initialize Miniconda
  shell: "/opt/miniconda/bin/conda init zsh"
