- name: Download Neovim archive
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/v0.9.4/nvim-linux64.tar.gz"
    dest: "/tmp/nvim-linux64.tar.gz"
    validate_certs: no

- name: Extract Neovim archive
  unarchive:
    src: "/tmp/nvim-linux64.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Ensure ~/.local directory exists
  file:
    path: "~/.local"
    state: directory
    mode: '0755'

- name: Move Neovim directory to ~/.local
  command: mv /tmp/nvim-linux64 ~/.local/

- name: Rename nvim-linux64 to nvim
  command: mv ~/.local/nvim-linux64 ~/.local/nvim

- name: Create Packer directory
  file:
    path: "/home/{{ ansible_user }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    state: directory

- name: Clone Packer
  git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "/home/{{ ansible_user }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    version: master

- name: Run PackerSync
  command: nvim --headless --noplugin -c "autocmd User PackerComplete quitall" -c "PackerSync"