- name: Download Neovim archive
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz"
    dest: "/tmp/nvim-linux64.tar.gz"
    validate_certs: no

- name: Extract Neovim archive
  unarchive:
    src: "/tmp/nvim-linux64.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Ensure .local directory exists
  file:
    path: "/home/{{ ansible_user }}/.local"
    state: directory
    mode: '0755'

- name: Move Neovim directory to .local
  command: mv /tmp/nvim-linux64 /home/{{ ansible_user }}/.local/

- name: Rename nvim-linux64 to nvim
  command: mv /home/{{ ansible_user }}/.local/nvim-linux64 /home/{{ ansible_user }}/.local/nvim
