- name: Create Neovim installation folder
  file:
    path: ~/.local/nvim
    state: directory

- name: Download Neovim
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/v0.8.3/nvim-linux64.tar.gz"
    dest: "/tmp/nvim-linux64.tar.gz"
    mode: '0755'

- name: Unpack Neovim
  unarchive:
    src: /tmp/nvim-linux64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move Neovim
  command:
    cmd: mv /tmp/nvim-linux64 ~/.local/nvim
    creates: ~/.local/nvim

- name: Clean downloaded file
  file:
    path: /tmp/nvim-linux64.tar.gz
    state: absent

- name: Create Packer directory
  file:
    path: "/home/{{ ansible_user }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    state: directory

- name: Clone Packer
  git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "/home/{{ ansible_user }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    version: master
