- name: Create Neovim installation folder
  shell: mkdir -p ~/.local

- name: Download Neovim
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/v0.8.3/nvim-linux64.tar.gz"
    dest: "/tmp/nvim-linux64.tar.gz"
    mode: '0755'

- name: Unpack Neovim
  shell: tar xzvf /tmp/nvim-linux64.tar.gz -C /tmp/

- name: Move Neovim
  shell: mv /tmp/nvim-linux64 ~/.local/nvim

- name: Clean downloaded file
  shell: rm /tmp/nvim-linux64.tar.gz

- name: Create Packer directory
  file:
    path: "/home/{{ ansible_user }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    state: directory

- name: Clone Packer
  git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "/home/{{ ansible_user }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    version: master
