- name: Install Neovim
  apt:
    name: neovim
    state: present

- name: Create Packer directory
  file:
    path: "/home/{{ ansible_user }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    state: directory

- name: Clone Packer
  git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "/home/{{ ansible_user }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    version: master

- name: Set Neovim as default editor
  alternatives:
    name: editor
    path: /usr/bin/nvim
    priority: 50
