- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"

- name: Install node
  shell: >
    . /home/{{ ansible_user }}/.nvm/nvm.sh && nvm install 18
  args:
    executable: /bin/bash
    chdir: "/home/{{ ansible_user }}/"
    creates: "/home/{{ ansible_user }}/.nvm/versions/{{ item }}"
  loop:
    - 14.20.0
