- name: Download n script
  get_url:
    url: https://raw.githubusercontent.com/tj/n/master/bin/n
    dest: /tmp/n
    mode: '0755'
  tags:
    - nodejs

- name: Install Node.js using n
  become: true
  command: bash /tmp/n lts
  tags:
    - nodejs

- name: Remove n script
  file:
    path: /tmp/n
    state: absent
  tags:
    - nodejs

- name: Install n using npm
  become: true
  npm:
    name: n
    global: yes
  tags:
    - nodejs
