- name: Install Node.js and NPM
  apt:
    name:
      - nodejs
      - npm
    state: present

- name: Install N Node Manager
  shell: "npm install -g n"

- name: Install Node.js version 18
  shell: "n 18"
