- name: Download n script
  get_url:
    url: https://raw.githubusercontent.com/tj/n/master/bin/n
    dest: /tmp/n
    mode: '0755'

- name: Install Node.js using n
  become: true
  command: bash /tmp/n lts

- name: Remove n script
  file:
    path: /tmp/n
    state: absent

- name: Install n using npm
  become: true
  command: npm install -g n
