- name: Install ESLint
  npm:
    name: eslint
    global: true

- name: Install TypeScript Language Server
  npm:
    name: typescript-language-server
    global: true

- name: Install TypeScript
  npm:
    name: typescript
    global: true
