- name: Copy SSH public key to target user's .ssh directory
  copy:
    src: "./.ssh/id_rsa"
    dest: "~/.ssh/"
    mode: "0600"

- name: Copy SSH public key to target user's .ssh directory
  copy:
    src: "./.ssh/id_rsa.pub"
    dest: "~/.ssh/"
    mode: "0644"

- name: Set the public key as the authorized key
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "~/.ssh/*.pub"
