- name: Copy SSH public key to target user's .ssh directory
  copy:
    src: "./.ssh/id_rsa"
    dest: "/home/{{ ansible_user }}/.ssh/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"

- name: Copy SSH public key to target user's .ssh directory
  copy:
    src: "./.ssh/id_rsa.pub"
    dest: "/home/{{ ansible_user }}/.ssh/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Set the public key as the authorized key
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "/home/{{ ansible_user }}/.ssh/*.pub"
