- name: Ensure .ssh directory exists.
  become: true
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0755
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh key
  become: true
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh key public
  become: true
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

- name: Check if SSH key exists for user
  stat:
    path: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
  register: ssh_key

- name: Print SSH key status
  debug:
    msg: "SSH key {{ 'exists' if ssh_key.stat.exists else 'does not exist' }} for user lucas"

- name: Set authorized key took from file
  become: true
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "/home/{{ user }}/.ssh/id_rsa.pub"
  with_fileglob:
  - "/home/{{ user }}/.ssh/*.pub"
