- name: Install tmux
  become: true
  apt:
    name: tmux
    state: present
  tags:
    - tmux

- name: Ensure tmux plugins directory exists
  file:
    path: "/home/{{ ansible_user }}/.tmux/plugins"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  tags:
    - tmux

- name: Install tmux plugin manager
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "/home/{{ ansible_user }}/.tmux/plugins/tpm"
    clone: yes
    update: yes
    force: yes
    accept_hostkey: yes
  tags:
    - tmux
