- name: Install Zsh dependencies
  become: true
  apt:
    name: zsh
    state: present
  tags:
    - zsh

- name: Change default shell
  become: true
  shell: chsh -s $(which zsh) "{{ ansible_user }}"
  tags:
    - zsh
