- name: Install Zsh dependencies
  become: true
  apt:
    name: zsh
    state: present

- name: Change default shell
  become: true
  shell: "chsh -s $(which zsh) {{ ansible_user }}"

- name: Set Zsh as default shell
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
    update_password: on_create
